<a href="https://colab.research.google.com/github/Pedr0bert/Machine-Learning/blob/main/MultiLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv("startups.csv")

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
print(X)

[[136897.8 165349.2 471784.1 'Paraná']
 [151377.59 162597.7 443898.53 'São Paulo']
 [101145.55 153441.51 407934.54 'Rio de Janeiro']
 [118671.85 144372.41 383199.62 'Paraná']
 [91391.77 142107.34 366168.42 'Rio de Janeiro']
 [99814.71 131876.9 362861.36 'Paraná']
 [147198.87 134615.46 127716.82 'São Paulo']
 [145530.06 130298.13 323876.68 'Rio de Janeiro']
 [148718.95 120542.52 311613.29 'Paraná']
 [108679.17 123334.88 304981.62 'São Paulo']
 [110594.11 101913.08 229160.95 'Rio de Janeiro']
 [91790.61 100671.96 249744.55 'São Paulo']
 [127320.38 93863.75 249839.44 'Rio de Janeiro']
 [135495.07 91992.39 252664.93 'São Paulo']
 [156547.42 119943.24 256512.92 'Rio de Janeiro']
 [122616.84 114523.61 261776.23 'Paraná']
 [121597.55 78013.11 264346.06 'São Paulo']
 [145077.58 94657.16 282574.31 'Paraná']
 [114175.79 91749.16 294919.57 'Rio de Janeiro']
 [153514.11 86419.7 0.0 'Paraná']
 [113867.3 76253.86 298664.47 'São Paulo']
 [153773.43 78389.47 299737.29 'Paraná']
 [122782.75 73994.56 30

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder="passthrough")
X = np.array(transformer.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 136897.8 165349.2 471784.1]
 [0.0 0.0 1.0 151377.59 162597.7 443898.53]
 [0.0 1.0 0.0 101145.55 153441.51 407934.54]
 [1.0 0.0 0.0 118671.85 144372.41 383199.62]
 [0.0 1.0 0.0 91391.77 142107.34 366168.42]
 [1.0 0.0 0.0 99814.71 131876.9 362861.36]
 [0.0 0.0 1.0 147198.87 134615.46 127716.82]
 [0.0 1.0 0.0 145530.06 130298.13 323876.68]
 [1.0 0.0 0.0 148718.95 120542.52 311613.29]
 [0.0 0.0 1.0 108679.17 123334.88 304981.62]
 [0.0 1.0 0.0 110594.11 101913.08 229160.95]
 [0.0 0.0 1.0 91790.61 100671.96 249744.55]
 [0.0 1.0 0.0 127320.38 93863.75 249839.44]
 [0.0 0.0 1.0 135495.07 91992.39 252664.93]
 [0.0 1.0 0.0 156547.42 119943.24 256512.92]
 [1.0 0.0 0.0 122616.84 114523.61 261776.23]
 [0.0 0.0 1.0 121597.55 78013.11 264346.06]
 [1.0 0.0 0.0 145077.58 94657.16 282574.31]
 [0.0 1.0 0.0 114175.79 91749.16 294919.57]
 [1.0 0.0 0.0 153514.11 86419.7 0.0]
 [0.0 0.0 1.0 113867.3 76253.86 298664.47]
 [1.0 0.0 0.0 153773.43 78389.47 299737.29]
 [0.0 1.0 0.0 122782.75 73994.56 3

In [ ]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state=0)

In [ ]:
regressor = LinearRegression()
regressor.fit(Xtrain, ytrain)

LinearRegression()

In [ ]:
y_pred = regressor.predict(Xtest)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), ytest.reshape(len(ytest),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [ ]:
for k in range(len(ytest)):
    y_teste = ytest[k]
    y_previsto = y_pred[k]
    erro = abs(((ytest[k] - y_pred[k])/ ytest[k]) *100)
    print(f'y_teste: {y_teste:.2f} y_previsto: {y_previsto:.2f} erro: {erro:.2f}')


y_teste: 103282.38 y_previsto: 103015.20 erro: 0.26
y_teste: 144259.40 y_previsto: 132582.28 erro: 8.09
y_teste: 146121.95 y_previsto: 132447.74 erro: 9.36
y_teste: 77798.83 y_previsto: 71976.10 erro: 7.48
y_teste: 191050.39 y_previsto: 178537.48 erro: 6.55
y_teste: 105008.31 y_previsto: 116161.24 erro: 10.62
y_teste: 81229.06 y_previsto: 67851.69 erro: 16.47
y_teste: 97483.56 y_previsto: 98791.73 erro: 1.34
y_teste: 110352.25 y_previsto: 113969.44 erro: 3.28
y_teste: 166187.94 y_previsto: 167921.07 erro: 1.04
